version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  marian-rebrow:
    image: marian/rebrow
    ports:
      - 5001:5001
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  dump-parser:
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    build:
      context: dump-parser/
      target: final
    environment:
      - REDIS_URL=redis://redis:6379/0
volumes:
  redis_data:
  postgres_data:
