version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  marian-rebrow:
    image: marian/rebrow
    ports:
      - 5001:5001
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  dump-parser:
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    build:
      context: dump-parser/
      target: final
    environment:
      - REDIS_URL=redis://redis:6379/0
volumes:
  redis_data:
