name: Publish Docker images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  push_to_registry:
    strategy:
      matrix:
        component: ['dump-parser', 'bot']
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet HEAD^ HEAD ./${{ matrix.component }}
          then
            echo "::set-output name=changed::false"
          else
            echo "::set-output name=changed::true"
          fi

      - name: Log in to GitHub Container Registry
        if: steps.check_changes.outputs.changed == 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push ${{ matrix.component }} to GitHub Packages
        if: steps.check_changes.outputs.changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.component }}/
          file: ./${{ matrix.component }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.component }}:${{ github.event.pull_request.number || 'latest' }}
