name: Build and Push Docker Images

on: [push, pull_request]

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      dump-parser: ${{ steps.changes.outputs.dump-parser }}
      bot: ${{ steps.changes.outputs.bot }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            bot:
              - 'bot/**'
            dump-parser:
              - 'dump-parser/**'

  push_to_registry:
    needs: check_changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: ['dump-parser', 'bot']
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ needs.check_changes.outputs[ matrix.component ] == 'true' }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.component }}:latest
        if: ${{ needs.check_changes.outputs[ matrix.component ] == 'true' }}