name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      dump-parser:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './dump-parser'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/devramsean0/Scryfall-Dump-Parser:latest
              docker push ghcr.io/devramsean0/Scryfall-Dump-Parser:latest