name: Publish Docker images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Dump-parser to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./dump-parser/
          file: ./dump-parser/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/dump-parser:latest
