name: Publish Docker images

on:
  push:
    paths:
      - 'dump-parser/**'
      - 'bot/**'
    branches: [ main ]
  workflow_dispatch:

jobs:
  push_to_registry:
    strategy:
      matrix:
        component: ['dump-parser', 'bot']
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push ${{ matrix.component }} to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.component }}/
          file: ./${{ matrix.component }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.component }}:latest